version: '2'
services:
   consumer:
     image: alvarobacelar/consumer-kafka-java:latest
     container_name: consumer-kafka
     environment:
       - KAFKA_SERVER={{ hostvars[groups['kafka'][0]]['ansible_host'] }}:9092
       - KAFKA_TOPIC=test-topic
       - KAFKA_COUNT_MSG=100
       - KAFKA_KEY=/root/client.truststore.jks
       - KAFKA_PASS={{ pass_key_kafka }}
